$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
# 無視するファイル
ignorePaths:
  - "**{json,yml,yaml}"
  - node_modules/**
  - dist/**
  - .cspell/**
  - .git/**
  - .vscode/**
  - docs/spec/site/**
  - coverage/**
  - src/libs/prisma/migrations/**
  - poc/**
  - sandbox/**
  - "**/storybook-static/**"
# 正規表現で無視する単語
ignoreRegExpList: []
# 正しいと見なす単語
words:
  - autoincrement
  - usecase
# 誤りと見なしたい単語
flagWords: []
# 無視する単語
ignoreWords: []
languageSettings:
  - languageId:
      - typescript
      - javascript
      - html
      - css
# 辞書パッケージ
dictionaryDefinitions:
  # 辞書ファイル名
  - name: domain
    # カスタム単語ファイルへのパス
    path: ./.cspell/domain.txt
    addWords: false
  - name: tech-terms
    path: ./.cspell/tech-terms.txt
    addWords: false
# 辞書
dictionaries:
  - typescript
  - javascript
  - html
  - css
  - node
  - npm
  - domain
  - tech-terms
