# Project information
site_name: ブックマークアプリ設計書
repo_url: https://github.com/Hitamuki/bookmark-manager-app
repo_name: bookmark-manager-app
site_description: ブックマークアプリの設計書
site_author: Hitamuki

# Contents Navigation
nav:
  - HOME:
      - はじめに:
          - index.md
          - 概要: 01-Home/概要_プロジェクト.md
      - 変更履歴:
          - 01-Home/変更履歴/CHANGELOG.md
      - バージョン履歴:
          - 01-Home/バージョン履歴/VersionHistory.md
          - v1.0:
              - 01-Home/バージョン履歴/v1.0/VersionHistory_v1.0.md
              - 01-Home/バージョン履歴/v1.0/リリースノート_v1.0.md
      - 用語集:
          - 01-Home/用語集/用語集.md
      - 開発者ガイド:
          - 01-Home/開発者ガイド/開発環境.md
          - 設計ルール:
              - 01-Home/開発者ガイド/設計ルール/設計ルール.md
          - 開発ルール:
              - 01-Home/開発者ガイド/開発ルール/コーディング規約.md
              - 01-Home/開発者ガイド/開発ルール/開発標準.md
  - 要件定義:
      - v1.0:
          - 概要: 03-要件定義/v1.0/概要_要件定義.md
          - 機能要件: 03-要件定義/v1.0/機能要件.md
          - 非機能要件: 03-要件定義/v1.0/非機能要件.md
  - 外部設計:
      - 概要: 04-外部設計/概要_外部設計.md
      - 共通仕様:
          - システム構成: 04-外部設計/共通仕様/システム構成.md
          - 権限: 04-外部設計/共通仕様/権限.md
          - DB設計:
              - 04-外部設計/共通仕様/DB設計/ER図.md
              - 04-外部設計/共通仕様/DB設計/テーブル定義書.md
      - 画面設計:
          - 04-外部設計/画面設計/画面一覧.md
          - 04-外部設計/画面設計/画面遷移図.md
          - 画面レイアウト:
              - 04-外部設計/画面設計/画面レイアウト/01_仮画面.md
      - 機能設計:
          - 04-外部設計/機能設計/機能一覧.md
          - 機能詳細:
              - 04-外部設計/機能設計/機能詳細/01_仮機能.md
      - API設計:
          - 04-外部設計/API設計/API一覧.md
      - テスト設計:
          - 04-外部設計/テスト設計/テスト設計.md
  - 内部設計:
      - 概要: 05-内部設計/概要_内部設計.md
      - 共通仕様:
          - 05-内部設計/共通仕様/共通仕様.md
          - 05-内部設計/共通仕様/アーキテクチャ設計.md
          - 05-内部設計/共通仕様/エラー設計.md
          - 05-内部設計/共通仕様/ログ設計.md
          - 05-内部設計/共通仕様/セキュリティ設計.md
          - 05-内部設計/共通仕様/パフォーマンス設計.md
      - DB設計:
          - 05-内部設計/DB設計/データベース設計.md
      - 画面設計:
          - 05-内部設計/画面設計/画面メッセージ一覧.md
          - 画面詳細:
              - 05-内部設計/画面設計/画面詳細/01_仮画面.md
      - API設計:
          - 05-内部設計/API設計/APIメッセージ一覧.md
          - API詳細:
              - 05-内部設計/API設計/API詳細/01_仮API.md
  - その他:
      - バッチ:
          - 10-その他/バッチ/バッチ一覧.md
      - ツール:
          - 10-その他/ツール/ツール一覧.md
      - 運用管理:
          - 10-その他/運用管理/障害対応.md
          - 10-その他/運用管理/監視.md

# Documentation and theme
docs_dir: "docs"
