/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bookmark Manager App API
 * APIドキュメント
 * OpenAPI spec version: v0.0
 */
import type { SampleDto } from './sampleDto';

export type SampleControllerSearchSamples200AllOf = {
  data?: SampleDto[];
};
