/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bookmark Manager App API
 * APIドキュメント
 * OpenAPI spec version: v0.0
 */
import type { PaginationDto } from './paginationDto';
import type { SampleControllerSearchSamples200AllOf } from './sampleControllerSearchSamples200AllOf';

export type SampleControllerSearchSamples200 = PaginationDto & SampleControllerSearchSamples200AllOf;
