export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

import '@/styles/globals.css';
import MswProvider from '@/providers/MswProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import ReactQueryProvider from '../providers/ReactQueryProvider';

// ルートレイアウト（全ページ共通）
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="flex min-h-screen flex-col">
        <MswProvider>
          <ReactQueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <header className="bg-gray-800 p-4 text-white">Header</header>
              <main className="container mx-auto flex-grow p-4">{children}</main>
              <footer className="bg-gray-800 p-4 text-white">Footer</footer>
            </ThemeProvider>
          </ReactQueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
