export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

import '@/styles/globals.css';
import { HeroUiProvider } from '@/providers/HeroUiProvider';
import MswProvider from '@/providers/MswProvider';
import ReactQueryProvider from '../providers/ReactQueryProvider';

// ルートレイアウト（全ページ共通）
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <MswProvider>
          <ReactQueryProvider>
            <HeroUiProvider>
              <header>Header</header>
              <main>{children}</main>
              <footer>Footer</footer>
            </HeroUiProvider>
          </ReactQueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
