/**
 * layout
 * モジュール定義
 */
export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

import '@/styles/globals.css';
import '@fontsource/noto-sans-jp/400.css';
import '@fontsource/noto-sans-jp/700.css';
import { HeroUiProvider } from '@/providers/HeroUiProvider';
import MswProvider from '@/providers/MswProvider';
import ReactQueryProvider from '../providers/ReactQueryProvider';

// ルートレイアウト（全ページ共通）
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" className="light" style={{ fontFamily: '"Noto Sans JP", sans-serif' }}>
      <body className="min-h-screen">
        <MswProvider>
          <ReactQueryProvider>
            <HeroUiProvider>
              <header className="p-4 bg-gray-100">Header</header>
              <main className="container mx-auto px-4 py-8 flex-grow">{children}</main>
              <footer className="p-4 bg-gray-100">Footer</footer>
            </HeroUiProvider>
          </ReactQueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
