### Fix
@baseUrl = http://localhost:3000/api
@contentType = application/json

### Variables

### Sample
# @name CreateSample
POST {{baseUrl}}/samples
Content-Type: {{contentType}}

{
  "title": "タイトル"
}
