### Fix
@baseUrl = http://localhost:4000/api
@contentType = application/json

### Variables
@sampleId = {{GetSamples.response.body.data.0.id}}

###
# @name GetSamples
GET {{baseUrl}}/samples

###
# @name GetSamples_Pagination
GET {{baseUrl}}/samples?limit=50&offset=0

###
# @name GetSample
GET {{baseUrl}}/samples/{{sampleId}}

###
# @name CreateSample
POST {{baseUrl}}/samples
Content-Type: {{contentType}}

{
  "title": "タイトル"
}

###
# @name UpdateSample
Put {{baseUrl}}/samples/{{sampleId}}
Content-Type: {{contentType}}

{
  "title": "タイトル更新"
}

###
# @name DeleteSample
DELETE {{baseUrl}}/samples/{{sampleId}}
